<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-brand" href="index.html">Order</a>
    </div>
    <?php require_once 'menu.php'?>
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <?php foreach ($menus as $menu):?>
                    <li>
                        <a class="<?php if ($menu['href'] != '#' && $_SERVER['REQUEST_URI'] == $menu['href']) echo 'active' ?>" href="<?php echo $menu['href']?>"><i class="<?php echo $menu['icon']?>"></i> <?php echo $menu['name'];?></a>
                        <?php if (isset($menu['children'])):?>
                            <ul class="nav nav-second-level">
                                <?php foreach ($menu['children'] as $children):?>
                                    <li>
                                        <a class="<?php if ($_SERVER['REQUEST_URI'] == $children['href']) echo 'active' ?>" href="<?php echo $children['href']?>"><?php echo $children['name'];?></a>
                                    </li>
                                <?php endforeach;?>
                            </ul>
                        <?php endif;?>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
</nav>