<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Order</title>
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
        <link href="/assets/css/plugins/timeline.css" rel="stylesheet">
        <link href="/assets/css/order.css" rel="stylesheet">
        <link href="/assets/css/plugins/morris.css" rel="stylesheet">
        <link href="/assets/css/select2.css" rel="stylesheet">
        <link href="/assets/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->menu->getMenu(); ?>
            <div id="page-wrapper" style="min-height: 629px;">
                <div class="row">
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
        </div>
        <script src="/assets/js/jquery.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/jquery-ui.min.js"></script>
        <script src="/assets/js/plugins/metisMenu/metisMenu.min.js"></script>
        <script src="/assets/js/plugins/morris/raphael.min.js"></script>
        <script src="/assets/js/plugins/morris/morris.min.js"></script>
        <script src="/assets/js/plugins/morris/morris-data.js"></script>
        <script src="/assets/js/order.js"></script>
        <script src="/assets/js/select2.js"></script>
        <script src="/assets/js/tinymce/tinymce.min.js"></script>
        <script src="/assets/js/jquery.form.js"></script>
        <script src="/assets/js/multimedia.js"></script>
        <script src="/assets/js/jquery.oLoader.min.js"></script>
        <script src="/assets/js/script.js"></script>
    </body>
</html>
