<?php

use Phalcon\Tag; ?>

<div class="row col-sm-12">
    <h1>Creating</h1>
    <?php echo $this->getContent(); ?>
    <div class="col-lg-12">
        <?php echo $this->tag->form(array('order/product/create/', 'method' => 'post', 'class' => 'form-horizontal', 'enctype' => "multipart/form-data")) ?>
        <div class="form-group">
            <label>Product name</label>
            <?php echo $form->render("title", array('class' => 'form-control', 'placeholder' => 'Product name')); ?>
        </div>
        <div class="form-group">
            <div class="col-lg-3">
                <label>Price</label>
                <?php echo $form->render("price", array('class' => 'form-control', 'placeholder' => 'Price')); ?>
            </div>
        </div>
        <div class="form-group">
            <label>Description</label>
            <?php echo $form->render("description", array('class' => 'tinyMce', "cols" => "100", "rows" => 10)); ?>
        </div>
        <div class="form-group">
            <?php require_once __DIR__ . '/../widgets/multimedia.phtml'; ?>
        </div>
        <div class="cntr">
            <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-primary")) ?>
        </div>
    <?php echo $this->tag->endForm() ?>
    <?php require_once __DIR__ . '/../widgets/upload_image.phtml'; ?>
  </div>
</div>