<?php

use Phalcon\Tag; ?>

<div class="row col-sm-12">
    <h1>Edit</h1>
    <?php echo $this->getContent(); ?>
    <?php if (isset($form)): ?>
        <?php echo $this->tag->form(array('order/orders/edit/' . $form->get('id')->getValue(), 'method' => 'post', 'class' => 'form-horizontal')) ?>
        <div class="col-lg-12">
            <div class="form-group">
                <div class="col-lg-1">
                    <label>User</label>
                </div>
                <div class="col-sm-4">
                    <?php echo $form->render("user_id", array('class' => 'form-control', 'placeholder' => 'User name')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-1">
                    <label>Product</label>
                </div>
                <div class="col-lg-4">
                    <?php echo $form->render("product_id", array('class' => 'form-control', 'placeholder' => 'Product')); ?>
                </div>
            </div>
            <div class="form-group">
              <div class="col-lg-1">
                <label>Quantity</label>
              </div>
              <div class="col-lg-4">
                <?php echo $form->render("quantity", array('class' => 'form-control', 'placeholder' => 'Quantity')); ?>
              </div>
            </div>
            <div class="cntr">
              <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-primary")) ?>
            </div>
        </div>
    <?php echo $this->tag->endForm() ?>
  <?php endif; ?>
</div>