<?php

use Phalcon\Tag; ?>

<div class="row col-sm-12">
    <h1>Creat</h1>
    <?php echo $this->getContent(); ?>

    <div class="col-lg-12">
        <?php echo $this->tag->form(array('order/user/create/', 'method' => 'post', 'class' => 'form-horizontal')) ?>
        <div class="form-group">
            <div class="col-lg-6">
                <label>First name</label>
                <?php echo $form->render("first_name", array('class' => 'form-control', 'placeholder' => 'First name')); ?>
            </div>
            <div class="col-lg-6">
                <label>Last name</label>
                <?php echo $form->render("last_name", array('class' => 'form-control', 'placeholder' => 'Last name')); ?>
            </div>
        </div>
        <div class="form-group">
            <label>Phone</label>
            <?php echo $form->render("phone", array('class' => 'form-control', 'placeholder' => 'Phone')); ?>
        </div>
        <div class="form-group">
            <label>Address</label>
            <?php echo $form->render("address", array('class' => 'tinyMce', "cols" => "100", "rows" => 10)); ?>
        </div>
        <div class="cntr">
            <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-primary")) ?>
        </div>
        <?php echo $this->tag->endForm() ?>
    </div>
</div>
